### ISSUE TITLE
Azure site is not logging

### ISSUE THREAD

**Issue by vaclav-antosik** [KPJS/blog#27]
Currently we are not able to read Azure logs. In case of error we have no idea what is happening there. Enable logging and find way how to read logs.

**Comment by yohny** [comment]
Its logging correctly now. The problem was that there were no logs because the application was never launched - Azure automatically searches for main entry point of application in order `server.js` and then  `app.js`, unless specified explicitly in package.json. We had no startup scrip specified so it used `server.js` which was not correct (for us its `app.js`) Once I specified it in 026d5c59fead235698360004e80457ab715353f5 everything works.
